version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - run: docker-compose build -f docker-compose-dev.yml -t bbb-lti-broker ./bbb-lti-broker/
      - run: docker images
      - run: docker tag bbb-lti-broker $DOCKER_USERNAME/bbb-lti-broker
      - run: docker push $DOCKER_USERNAME/bbb-lti-broker

  test:
    machine: true
    steps:
      - run: docker-compose pull 
      - run: docker-compose run app rake db:create
      - run: docker-compose run app rake db:migrate
      - run: docker-compose run app rake db:seed
      - run: docker-compose up -d
      - run: docker-compose down
workflows:
  version: 2
  build_and_test:
    jobs:
      - build

