version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker-compose build 
      - run: docker-compose run app rake db:create
      - run: docker-compose run app rake db:migrate
      - run: docker-compose run app rake db:seed
      - run:
          command: |
            docker-compose up
            docker-compose down
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
