---
version: 2
jobs:
  build:
    working_directory: ~/bbb-lti-broker
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
        environment:
          PGHOST: localhost
          PGUSER: bbb-lti-broker
          RAILS_ENV: test
          DATABASE_URL: "postgresql://postgres:password@localhost"
      - image: postgres:11
        environment:
          POSTGRES_PASSWORD: password
    steps:
      - checkout

      # Restore Cached Dependencies
      - type: cache-restore
        name: Restore bundle cache
        key: bbb-lti-broker-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Cache Dependencies
      - type: cache-save
        name: Store bundle cache
        key: bbb-lti-broker-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      # Wait for DB
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m

      # Setup the environment
      - run: cp dotenv .env

      # Setup the database
      - run: bundle exec rake db:setup

      # Run the tests
      - run: bundle exec rails test:db
