version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker-compose build -t bbb-lti-broker ./
      - run: docker-compose run bundle install
      - run: docker-compose exec rake db:create
      - run: docker-compose exec rake db:migrate
      - run: docker-compose exec rake db:seed
      - run: docker-compose up
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
