code: rooms
name:
  default_value: rooms
  key: rooms.name

description:
  default_value: Launch into rooms.
  key: rooms.description

messages:
  - type: basic-lti-launch-request
    route:
      path: "/rooms"
      controller: message
      action: basic_lti_launch_request
    parameters:
      - name: "app"
        fixed: "rooms"
    required_capabilities:
      - basic-lti-launch-request
      - Membership.role
      - Context.id
      - Context.title
      - User.id
      - User.username
      - Person.name.full
      - Person.name.given
      - Person.name.family
### List of parameters ###
#     parameters:
#      - name: #the name of the parameter
#        fixed: #a fixed value you want to substitute in
#      - name: #the name of the parameter
#        variable: #the variable substitution that you want to get
#        required: #set to true if you want registration to fail if not the variable is not available
### List of required capabilities ###
#    required_capabilities:
#      - #name of a required capability
### List of optional capabilities ###
#    optional_capabilities:
#      - #name of a optional capability