default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: postgres
  password: password
  host: postgres

development:
  <<: *default
  database: bbb_lti_broker_development

test:
  <<: *default
  database: bbb_lti_broker_test

production:
  <<: *default
  database: bbb_lti_broker
