default: &default
  encoding: unicode
  adapter: postgresql
<<<<<<< HEAD
  host: ''
=======
  host: localhost
>>>>>>> f9729ff90e29266ceece26f88ce6ca02a0891066
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  pool: 5
  timeout: 5000
  url: <%= ENV['DATABASE_URL'] || 'postgres://localhost:5432' %>

development:
  <<: *default
  database: bbb_lti_broker_development

test:
  <<: *default
  database: bbb_lti_broker_test

production:
  <<: *default
  database: bbb_lti_broker
