default: &default
  encoding: unicode
  adapter: postgresql
  host: ''
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  pool: 5
  timeout: 5000
  url: <%= ENV['DATABASE_URL'] || 'postgres://localhost:5432' %>

development:
  <<: *default
  database: bbb_lti_broker_development

test:
  <<: *default
  database: bbb_lti_broker_test

production:
  <<: *default
  database: bbb_lti_broker
