default: &default
  encoding: unicode
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: bbb_lti_broker_development

test:
  <<: *default
  database: bbb_lti_broker_test

production:
  <<: *default
  database: bbb_lti_broker
